version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hexo-all-minifier
    versions:
    - 0.5.6
  - dependency-name: highlight.js
    versions:
    - 10.7.1
- package-ecosystem: npm
  directory: "/themes/sagiri"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.35.0
